// Reference: http://flatuicolors.co/

export const TURQUOISE = '#1ABC9C'
export const GREEN_SEA = '#16A085'
export const EMERALD = '#2ECC71'
export const NEPHRITIS = '#27AE60'
export const PETER_RIVER = '#3498DB'
export const BELIZE_HOLE = '#2980B9'
export const AMETHYST = '#9B59B6'
export const WISTERIA = '#8E44AD'
export const WET_ASPHALT = '#34495E'
export const MIDNIGHT_BLUE = '#2C3E50'
export const SUN_FLOWER = '#F1C40F'
export const ORANGE = '#F39C12'
export const CARROT = '#E67E22'
export const PUMPKIN = '#D35400'
export const ALIZARIN = '#E74C3C'
export const POMEGRANATE = '#C0392B'
export const CLOUDS = '#ECF0F1'
export const SILVER = '#BDC3C7'
export const CONCRETE = '#95A5A6'
export const ASBESTOS = '#7F8C8D'
